name: Dependabot Auto-Merge

on:
  workflow_run:
    workflows:
      - Tests
    types:
      - completed

jobs:
  # Merge dependabot PR's after tests pass.
  automerge:
    if: ${{ github.actor == 'dependabot[bot]' && github.event.workflow_run.conclusion == 'success' && github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    steps:
      - name: Automatically merge dependabot updates
        uses: ahmadnassri/action-dependabot-auto-merge@v2
        with:
          target: minor
          github-token: ${{ secrets.DEPENDABOT_AUTOMERGE }}
