name: Dependabot PR

on:
  workflow_dispatch:
    branches:
      - 'dependabot/**'
  pull_request:
    branches:
      - 'dependabot/**'

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  # This job lints all files with ESLint.
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Lint files
        run: npm run lint

  # This job runs all Cypress tests.
  cypress-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          # TODO: Re-enable once a public release of the library is available.
          # Mac and windows env's take significantly longer to run.
          # - macos-latest
          # - windows-latest
        node:
          - 14
          - 16
          - 18

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: E2E tests on Node v${{ matrix.node }}
        run: npm run test:e2e

      - name: Component tests on Node v${{ matrix.node }}
        run: npm run test:component
