name: Docs

on:
  push:
    tags:
      - v*

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Generate documentation
        run: npm run build-storybook

      - name: Publish documentation
        uses: JamesIves/github-pages-deploy-action@4
        with:
          branch: gh-pages
          folder: storybook-static
          clean: true
